//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBlankForm.Droid.ws.petango.com {
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsAdoptionSoap", Namespace="http://www.petango.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HappyTailListItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class WsAdoption : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MedicalViewReportPdfOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdoptionDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdoptionListOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdoptableSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdoptableSearchWithStageOperationCompleted;
        
        private System.Threading.SendOrPostCallback AdoptableDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback foundSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback foundSearchForCompanyGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback foundSearchForCompanyGroupPageableOperationCompleted;
        
        private System.Threading.SendOrPostCallback foundSearchWithSiteOperationCompleted;
        
        private System.Threading.SendOrPostCallback lostSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback lostSearchForCompanyGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback lostSearchForCompanyGroupPageableOperationCompleted;
        
        private System.Threading.SendOrPostCallback foundDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback foundDetailsForCompanyGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback lostDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback lostDetailsForCompanyGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback HappyTailListOperationCompleted;
        
        private System.Threading.SendOrPostCallback HappyTailDetailsOperationCompleted;
        
        /// CodeRemarks
        public WsAdoption() {
            this.Url = "http://wspetangoprd2.azurewebsites.net/webservices/wsadoption.asmx";
        }
        
        public WsAdoption(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event MedicalViewReportPdfCompletedEventHandler MedicalViewReportPdfCompleted;
        
        /// CodeRemarks
        public event AdoptionDetailsCompletedEventHandler AdoptionDetailsCompleted;
        
        /// CodeRemarks
        public event AdoptionListCompletedEventHandler AdoptionListCompleted;
        
        /// CodeRemarks
        public event AdoptableSearchCompletedEventHandler AdoptableSearchCompleted;
        
        /// CodeRemarks
        public event AdoptableSearchWithStageCompletedEventHandler AdoptableSearchWithStageCompleted;
        
        /// CodeRemarks
        public event AdoptableDetailsCompletedEventHandler AdoptableDetailsCompleted;
        
        /// CodeRemarks
        public event foundSearchCompletedEventHandler foundSearchCompleted;
        
        /// CodeRemarks
        public event foundSearchForCompanyGroupCompletedEventHandler foundSearchForCompanyGroupCompleted;
        
        /// CodeRemarks
        public event foundSearchForCompanyGroupPageableCompletedEventHandler foundSearchForCompanyGroupPageableCompleted;
        
        /// CodeRemarks
        public event foundSearchWithSiteCompletedEventHandler foundSearchWithSiteCompleted;
        
        /// CodeRemarks
        public event lostSearchCompletedEventHandler lostSearchCompleted;
        
        /// CodeRemarks
        public event lostSearchForCompanyGroupCompletedEventHandler lostSearchForCompanyGroupCompleted;
        
        /// CodeRemarks
        public event lostSearchForCompanyGroupPageableCompletedEventHandler lostSearchForCompanyGroupPageableCompleted;
        
        /// CodeRemarks
        public event foundDetailsCompletedEventHandler foundDetailsCompleted;
        
        /// CodeRemarks
        public event foundDetailsForCompanyGroupCompletedEventHandler foundDetailsForCompanyGroupCompleted;
        
        /// CodeRemarks
        public event lostDetailsCompletedEventHandler lostDetailsCompleted;
        
        /// CodeRemarks
        public event lostDetailsForCompanyGroupCompletedEventHandler lostDetailsForCompanyGroupCompleted;
        
        /// CodeRemarks
        public event HappyTailListCompletedEventHandler HappyTailListCompleted;
        
        /// CodeRemarks
        public event HappyTailDetailsCompletedEventHandler HappyTailDetailsCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/MedicalViewReportPdf", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool MedicalViewReportPdf(int animalID, string authKey, string ftpDestination) {
            object[] results = this.Invoke("MedicalViewReportPdf", new object[] {
                        animalID,
                        authKey,
                        ftpDestination});
            return ((bool)(results[0]));
        }
        
        /// CodeRemarks
        public void MedicalViewReportPdfAsync(int animalID, string authKey, string ftpDestination) {
            this.MedicalViewReportPdfAsync(animalID, authKey, ftpDestination, null);
        }
        
        /// CodeRemarks
        public void MedicalViewReportPdfAsync(int animalID, string authKey, string ftpDestination, object userState) {
            if ((this.MedicalViewReportPdfOperationCompleted == null)) {
                this.MedicalViewReportPdfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMedicalViewReportPdfOperationCompleted);
            }
            this.InvokeAsync("MedicalViewReportPdf", new object[] {
                        animalID,
                        authKey,
                        ftpDestination}, this.MedicalViewReportPdfOperationCompleted, userState);
        }
        
        private void OnMedicalViewReportPdfOperationCompleted(object arg) {
            if ((this.MedicalViewReportPdfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MedicalViewReportPdfCompleted(this, new MedicalViewReportPdfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/AdoptionDetails", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AdoptionDetails(int animalID, string authKey) {
            object[] results = this.Invoke("AdoptionDetails", new object[] {
                        animalID,
                        authKey});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// CodeRemarks
        public void AdoptionDetailsAsync(int animalID, string authKey) {
            this.AdoptionDetailsAsync(animalID, authKey, null);
        }
        
        /// CodeRemarks
        public void AdoptionDetailsAsync(int animalID, string authKey, object userState) {
            if ((this.AdoptionDetailsOperationCompleted == null)) {
                this.AdoptionDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdoptionDetailsOperationCompleted);
            }
            this.InvokeAsync("AdoptionDetails", new object[] {
                        animalID,
                        authKey}, this.AdoptionDetailsOperationCompleted, userState);
        }
        
        private void OnAdoptionDetailsOperationCompleted(object arg) {
            if ((this.AdoptionDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdoptionDetailsCompleted(this, new AdoptionDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/AdoptionList", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode[] AdoptionList(string authKey, System.DateTime adoptionDate, string siteID) {
            object[] results = this.Invoke("AdoptionList", new object[] {
                        authKey,
                        adoptionDate,
                        siteID});
            return ((System.Xml.XmlNode[])(results[0]));
        }
        
        /// CodeRemarks
        public void AdoptionListAsync(string authKey, System.DateTime adoptionDate, string siteID) {
            this.AdoptionListAsync(authKey, adoptionDate, siteID, null);
        }
        
        /// CodeRemarks
        public void AdoptionListAsync(string authKey, System.DateTime adoptionDate, string siteID, object userState) {
            if ((this.AdoptionListOperationCompleted == null)) {
                this.AdoptionListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdoptionListOperationCompleted);
            }
            this.InvokeAsync("AdoptionList", new object[] {
                        authKey,
                        adoptionDate,
                        siteID}, this.AdoptionListOperationCompleted, userState);
        }
        
        private void OnAdoptionListOperationCompleted(object arg) {
            if ((this.AdoptionListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdoptionListCompleted(this, new AdoptionListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/AdoptableSearch", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode[] AdoptableSearch(string authkey, string speciesID, string sex, string ageGroup, string location, string site, string onHold, string orderBy, string primaryBreed, string secondaryBreed, string specialNeeds, string noDogs, string noCats, string noKids, string stageID) {
            object[] results = this.Invoke("AdoptableSearch", new object[] {
                        authkey,
                        speciesID,
                        sex,
                        ageGroup,
                        location,
                        site,
                        onHold,
                        orderBy,
                        primaryBreed,
                        secondaryBreed,
                        specialNeeds,
                        noDogs,
                        noCats,
                        noKids,
                        stageID});
            return ((System.Xml.XmlNode[])(results[0]));
        }
        
        /// CodeRemarks
        public void AdoptableSearchAsync(string authkey, string speciesID, string sex, string ageGroup, string location, string site, string onHold, string orderBy, string primaryBreed, string secondaryBreed, string specialNeeds, string noDogs, string noCats, string noKids, string stageID) {
            this.AdoptableSearchAsync(authkey, speciesID, sex, ageGroup, location, site, onHold, orderBy, primaryBreed, secondaryBreed, specialNeeds, noDogs, noCats, noKids, stageID, null);
        }
        
        /// CodeRemarks
        public void AdoptableSearchAsync(
                    string authkey, 
                    string speciesID, 
                    string sex, 
                    string ageGroup, 
                    string location, 
                    string site, 
                    string onHold, 
                    string orderBy, 
                    string primaryBreed, 
                    string secondaryBreed, 
                    string specialNeeds, 
                    string noDogs, 
                    string noCats, 
                    string noKids, 
                    string stageID, 
                    object userState) {
            if ((this.AdoptableSearchOperationCompleted == null)) {
                this.AdoptableSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdoptableSearchOperationCompleted);
            }
            this.InvokeAsync("AdoptableSearch", new object[] {
                        authkey,
                        speciesID,
                        sex,
                        ageGroup,
                        location,
                        site,
                        onHold,
                        orderBy,
                        primaryBreed,
                        secondaryBreed,
                        specialNeeds,
                        noDogs,
                        noCats,
                        noKids,
                        stageID}, this.AdoptableSearchOperationCompleted, userState);
        }
        
        private void OnAdoptableSearchOperationCompleted(object arg) {
            if ((this.AdoptableSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdoptableSearchCompleted(this, new AdoptableSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/AdoptableSearchWithStage", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode[] AdoptableSearchWithStage(
                    string authkey, 
                    string speciesID, 
                    string sex, 
                    string ageGroup, 
                    string location, 
                    string site, 
                    string onHold, 
                    string orderBy, 
                    string primaryBreed, 
                    string secondaryBreed, 
                    string specialNeeds, 
                    string noDogs, 
                    string noCats, 
                    string noKids, 
                    string stageID, 
                    string featured) {
            object[] results = this.Invoke("AdoptableSearchWithStage", new object[] {
                        authkey,
                        speciesID,
                        sex,
                        ageGroup,
                        location,
                        site,
                        onHold,
                        orderBy,
                        primaryBreed,
                        secondaryBreed,
                        specialNeeds,
                        noDogs,
                        noCats,
                        noKids,
                        stageID,
                        featured});
            return ((System.Xml.XmlNode[])(results[0]));
        }
        
        /// CodeRemarks
        public void AdoptableSearchWithStageAsync(
                    string authkey, 
                    string speciesID, 
                    string sex, 
                    string ageGroup, 
                    string location, 
                    string site, 
                    string onHold, 
                    string orderBy, 
                    string primaryBreed, 
                    string secondaryBreed, 
                    string specialNeeds, 
                    string noDogs, 
                    string noCats, 
                    string noKids, 
                    string stageID, 
                    string featured) {
            this.AdoptableSearchWithStageAsync(authkey, speciesID, sex, ageGroup, location, site, onHold, orderBy, primaryBreed, secondaryBreed, specialNeeds, noDogs, noCats, noKids, stageID, featured, null);
        }
        
        /// CodeRemarks
        public void AdoptableSearchWithStageAsync(
                    string authkey, 
                    string speciesID, 
                    string sex, 
                    string ageGroup, 
                    string location, 
                    string site, 
                    string onHold, 
                    string orderBy, 
                    string primaryBreed, 
                    string secondaryBreed, 
                    string specialNeeds, 
                    string noDogs, 
                    string noCats, 
                    string noKids, 
                    string stageID, 
                    string featured, 
                    object userState) {
            if ((this.AdoptableSearchWithStageOperationCompleted == null)) {
                this.AdoptableSearchWithStageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdoptableSearchWithStageOperationCompleted);
            }
            this.InvokeAsync("AdoptableSearchWithStage", new object[] {
                        authkey,
                        speciesID,
                        sex,
                        ageGroup,
                        location,
                        site,
                        onHold,
                        orderBy,
                        primaryBreed,
                        secondaryBreed,
                        specialNeeds,
                        noDogs,
                        noCats,
                        noKids,
                        stageID,
                        featured}, this.AdoptableSearchWithStageOperationCompleted, userState);
        }
        
        private void OnAdoptableSearchWithStageOperationCompleted(object arg) {
            if ((this.AdoptableSearchWithStageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdoptableSearchWithStageCompleted(this, new AdoptableSearchWithStageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/AdoptableDetails", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode AdoptableDetails(string animalID, string authkey) {
            object[] results = this.Invoke("AdoptableDetails", new object[] {
                        animalID,
                        authkey});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// CodeRemarks
        public void AdoptableDetailsAsync(string animalID, string authkey) {
            this.AdoptableDetailsAsync(animalID, authkey, null);
        }
        
        /// CodeRemarks
        public void AdoptableDetailsAsync(string animalID, string authkey, object userState) {
            if ((this.AdoptableDetailsOperationCompleted == null)) {
                this.AdoptableDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdoptableDetailsOperationCompleted);
            }
            this.InvokeAsync("AdoptableDetails", new object[] {
                        animalID,
                        authkey}, this.AdoptableDetailsOperationCompleted, userState);
        }
        
        private void OnAdoptableDetailsOperationCompleted(object arg) {
            if ((this.AdoptableDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AdoptableDetailsCompleted(this, new AdoptableDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/foundSearch", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode[] foundSearch(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int searchOption) {
            object[] results = this.Invoke("foundSearch", new object[] {
                        speciesID,
                        sex,
                        ageGroup,
                        authkey,
                        orderBy,
                        searchOption});
            return ((System.Xml.XmlNode[])(results[0]));
        }
        
        /// CodeRemarks
        public void foundSearchAsync(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int searchOption) {
            this.foundSearchAsync(speciesID, sex, ageGroup, authkey, orderBy, searchOption, null);
        }
        
        /// CodeRemarks
        public void foundSearchAsync(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int searchOption, object userState) {
            if ((this.foundSearchOperationCompleted == null)) {
                this.foundSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfoundSearchOperationCompleted);
            }
            this.InvokeAsync("foundSearch", new object[] {
                        speciesID,
                        sex,
                        ageGroup,
                        authkey,
                        orderBy,
                        searchOption}, this.foundSearchOperationCompleted, userState);
        }
        
        private void OnfoundSearchOperationCompleted(object arg) {
            if ((this.foundSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.foundSearchCompleted(this, new foundSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/foundSearchForCompanyGroup", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode[] foundSearchForCompanyGroup(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int searchOption) {
            object[] results = this.Invoke("foundSearchForCompanyGroup", new object[] {
                        speciesID,
                        sex,
                        ageGroup,
                        authkey,
                        orderBy,
                        searchOption});
            return ((System.Xml.XmlNode[])(results[0]));
        }
        
        /// CodeRemarks
        public void foundSearchForCompanyGroupAsync(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int searchOption) {
            this.foundSearchForCompanyGroupAsync(speciesID, sex, ageGroup, authkey, orderBy, searchOption, null);
        }
        
        /// CodeRemarks
        public void foundSearchForCompanyGroupAsync(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int searchOption, object userState) {
            if ((this.foundSearchForCompanyGroupOperationCompleted == null)) {
                this.foundSearchForCompanyGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfoundSearchForCompanyGroupOperationCompleted);
            }
            this.InvokeAsync("foundSearchForCompanyGroup", new object[] {
                        speciesID,
                        sex,
                        ageGroup,
                        authkey,
                        orderBy,
                        searchOption}, this.foundSearchForCompanyGroupOperationCompleted, userState);
        }
        
        private void OnfoundSearchForCompanyGroupOperationCompleted(object arg) {
            if ((this.foundSearchForCompanyGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.foundSearchForCompanyGroupCompleted(this, new foundSearchForCompanyGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/foundSearchForCompanyGroupPageable", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode[] foundSearchForCompanyGroupPageable(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int searchOption, int skip, int take) {
            object[] results = this.Invoke("foundSearchForCompanyGroupPageable", new object[] {
                        speciesID,
                        sex,
                        ageGroup,
                        authkey,
                        orderBy,
                        searchOption,
                        skip,
                        take});
            return ((System.Xml.XmlNode[])(results[0]));
        }
        
        /// CodeRemarks
        public void foundSearchForCompanyGroupPageableAsync(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int searchOption, int skip, int take) {
            this.foundSearchForCompanyGroupPageableAsync(speciesID, sex, ageGroup, authkey, orderBy, searchOption, skip, take, null);
        }
        
        /// CodeRemarks
        public void foundSearchForCompanyGroupPageableAsync(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int searchOption, int skip, int take, object userState) {
            if ((this.foundSearchForCompanyGroupPageableOperationCompleted == null)) {
                this.foundSearchForCompanyGroupPageableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfoundSearchForCompanyGroupPageableOperationCompleted);
            }
            this.InvokeAsync("foundSearchForCompanyGroupPageable", new object[] {
                        speciesID,
                        sex,
                        ageGroup,
                        authkey,
                        orderBy,
                        searchOption,
                        skip,
                        take}, this.foundSearchForCompanyGroupPageableOperationCompleted, userState);
        }
        
        private void OnfoundSearchForCompanyGroupPageableOperationCompleted(object arg) {
            if ((this.foundSearchForCompanyGroupPageableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.foundSearchForCompanyGroupPageableCompleted(this, new foundSearchForCompanyGroupPageableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/foundSearchWithSite", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode[] foundSearchWithSite(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int searchOption, int siteID) {
            object[] results = this.Invoke("foundSearchWithSite", new object[] {
                        speciesID,
                        sex,
                        ageGroup,
                        authkey,
                        orderBy,
                        searchOption,
                        siteID});
            return ((System.Xml.XmlNode[])(results[0]));
        }
        
        /// CodeRemarks
        public void foundSearchWithSiteAsync(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int searchOption, int siteID) {
            this.foundSearchWithSiteAsync(speciesID, sex, ageGroup, authkey, orderBy, searchOption, siteID, null);
        }
        
        /// CodeRemarks
        public void foundSearchWithSiteAsync(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int searchOption, int siteID, object userState) {
            if ((this.foundSearchWithSiteOperationCompleted == null)) {
                this.foundSearchWithSiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfoundSearchWithSiteOperationCompleted);
            }
            this.InvokeAsync("foundSearchWithSite", new object[] {
                        speciesID,
                        sex,
                        ageGroup,
                        authkey,
                        orderBy,
                        searchOption,
                        siteID}, this.foundSearchWithSiteOperationCompleted, userState);
        }
        
        private void OnfoundSearchWithSiteOperationCompleted(object arg) {
            if ((this.foundSearchWithSiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.foundSearchWithSiteCompleted(this, new foundSearchWithSiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/lostSearch", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode[] lostSearch(int speciesID, string sex, string ageGroup, string authkey, string orderBy) {
            object[] results = this.Invoke("lostSearch", new object[] {
                        speciesID,
                        sex,
                        ageGroup,
                        authkey,
                        orderBy});
            return ((System.Xml.XmlNode[])(results[0]));
        }
        
        /// CodeRemarks
        public void lostSearchAsync(int speciesID, string sex, string ageGroup, string authkey, string orderBy) {
            this.lostSearchAsync(speciesID, sex, ageGroup, authkey, orderBy, null);
        }
        
        /// CodeRemarks
        public void lostSearchAsync(int speciesID, string sex, string ageGroup, string authkey, string orderBy, object userState) {
            if ((this.lostSearchOperationCompleted == null)) {
                this.lostSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlostSearchOperationCompleted);
            }
            this.InvokeAsync("lostSearch", new object[] {
                        speciesID,
                        sex,
                        ageGroup,
                        authkey,
                        orderBy}, this.lostSearchOperationCompleted, userState);
        }
        
        private void OnlostSearchOperationCompleted(object arg) {
            if ((this.lostSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lostSearchCompleted(this, new lostSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/lostSearchForCompanyGroup", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode[] lostSearchForCompanyGroup(int speciesID, string sex, string ageGroup, string authkey, string orderBy) {
            object[] results = this.Invoke("lostSearchForCompanyGroup", new object[] {
                        speciesID,
                        sex,
                        ageGroup,
                        authkey,
                        orderBy});
            return ((System.Xml.XmlNode[])(results[0]));
        }
        
        /// CodeRemarks
        public void lostSearchForCompanyGroupAsync(int speciesID, string sex, string ageGroup, string authkey, string orderBy) {
            this.lostSearchForCompanyGroupAsync(speciesID, sex, ageGroup, authkey, orderBy, null);
        }
        
        /// CodeRemarks
        public void lostSearchForCompanyGroupAsync(int speciesID, string sex, string ageGroup, string authkey, string orderBy, object userState) {
            if ((this.lostSearchForCompanyGroupOperationCompleted == null)) {
                this.lostSearchForCompanyGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlostSearchForCompanyGroupOperationCompleted);
            }
            this.InvokeAsync("lostSearchForCompanyGroup", new object[] {
                        speciesID,
                        sex,
                        ageGroup,
                        authkey,
                        orderBy}, this.lostSearchForCompanyGroupOperationCompleted, userState);
        }
        
        private void OnlostSearchForCompanyGroupOperationCompleted(object arg) {
            if ((this.lostSearchForCompanyGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lostSearchForCompanyGroupCompleted(this, new lostSearchForCompanyGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/lostSearchForCompanyGroupPageable", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode[] lostSearchForCompanyGroupPageable(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int skip, int take) {
            object[] results = this.Invoke("lostSearchForCompanyGroupPageable", new object[] {
                        speciesID,
                        sex,
                        ageGroup,
                        authkey,
                        orderBy,
                        skip,
                        take});
            return ((System.Xml.XmlNode[])(results[0]));
        }
        
        /// CodeRemarks
        public void lostSearchForCompanyGroupPageableAsync(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int skip, int take) {
            this.lostSearchForCompanyGroupPageableAsync(speciesID, sex, ageGroup, authkey, orderBy, skip, take, null);
        }
        
        /// CodeRemarks
        public void lostSearchForCompanyGroupPageableAsync(int speciesID, string sex, string ageGroup, string authkey, string orderBy, int skip, int take, object userState) {
            if ((this.lostSearchForCompanyGroupPageableOperationCompleted == null)) {
                this.lostSearchForCompanyGroupPageableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlostSearchForCompanyGroupPageableOperationCompleted);
            }
            this.InvokeAsync("lostSearchForCompanyGroupPageable", new object[] {
                        speciesID,
                        sex,
                        ageGroup,
                        authkey,
                        orderBy,
                        skip,
                        take}, this.lostSearchForCompanyGroupPageableOperationCompleted, userState);
        }
        
        private void OnlostSearchForCompanyGroupPageableOperationCompleted(object arg) {
            if ((this.lostSearchForCompanyGroupPageableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lostSearchForCompanyGroupPageableCompleted(this, new lostSearchForCompanyGroupPageableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/foundDetails", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode foundDetails(int animalID, string authkey) {
            object[] results = this.Invoke("foundDetails", new object[] {
                        animalID,
                        authkey});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// CodeRemarks
        public void foundDetailsAsync(int animalID, string authkey) {
            this.foundDetailsAsync(animalID, authkey, null);
        }
        
        /// CodeRemarks
        public void foundDetailsAsync(int animalID, string authkey, object userState) {
            if ((this.foundDetailsOperationCompleted == null)) {
                this.foundDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfoundDetailsOperationCompleted);
            }
            this.InvokeAsync("foundDetails", new object[] {
                        animalID,
                        authkey}, this.foundDetailsOperationCompleted, userState);
        }
        
        private void OnfoundDetailsOperationCompleted(object arg) {
            if ((this.foundDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.foundDetailsCompleted(this, new foundDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/foundDetailsForCompanyGroup", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode foundDetailsForCompanyGroup(int animalID, string authkey) {
            object[] results = this.Invoke("foundDetailsForCompanyGroup", new object[] {
                        animalID,
                        authkey});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// CodeRemarks
        public void foundDetailsForCompanyGroupAsync(int animalID, string authkey) {
            this.foundDetailsForCompanyGroupAsync(animalID, authkey, null);
        }
        
        /// CodeRemarks
        public void foundDetailsForCompanyGroupAsync(int animalID, string authkey, object userState) {
            if ((this.foundDetailsForCompanyGroupOperationCompleted == null)) {
                this.foundDetailsForCompanyGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfoundDetailsForCompanyGroupOperationCompleted);
            }
            this.InvokeAsync("foundDetailsForCompanyGroup", new object[] {
                        animalID,
                        authkey}, this.foundDetailsForCompanyGroupOperationCompleted, userState);
        }
        
        private void OnfoundDetailsForCompanyGroupOperationCompleted(object arg) {
            if ((this.foundDetailsForCompanyGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.foundDetailsForCompanyGroupCompleted(this, new foundDetailsForCompanyGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/lostDetails", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode lostDetails(int animalID, string authkey) {
            object[] results = this.Invoke("lostDetails", new object[] {
                        animalID,
                        authkey});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// CodeRemarks
        public void lostDetailsAsync(int animalID, string authkey) {
            this.lostDetailsAsync(animalID, authkey, null);
        }
        
        /// CodeRemarks
        public void lostDetailsAsync(int animalID, string authkey, object userState) {
            if ((this.lostDetailsOperationCompleted == null)) {
                this.lostDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlostDetailsOperationCompleted);
            }
            this.InvokeAsync("lostDetails", new object[] {
                        animalID,
                        authkey}, this.lostDetailsOperationCompleted, userState);
        }
        
        private void OnlostDetailsOperationCompleted(object arg) {
            if ((this.lostDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lostDetailsCompleted(this, new lostDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/lostDetailsForCompanyGroup", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode lostDetailsForCompanyGroup(int animalID, string authkey) {
            object[] results = this.Invoke("lostDetailsForCompanyGroup", new object[] {
                        animalID,
                        authkey});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// CodeRemarks
        public void lostDetailsForCompanyGroupAsync(int animalID, string authkey) {
            this.lostDetailsForCompanyGroupAsync(animalID, authkey, null);
        }
        
        /// CodeRemarks
        public void lostDetailsForCompanyGroupAsync(int animalID, string authkey, object userState) {
            if ((this.lostDetailsForCompanyGroupOperationCompleted == null)) {
                this.lostDetailsForCompanyGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlostDetailsForCompanyGroupOperationCompleted);
            }
            this.InvokeAsync("lostDetailsForCompanyGroup", new object[] {
                        animalID,
                        authkey}, this.lostDetailsForCompanyGroupOperationCompleted, userState);
        }
        
        private void OnlostDetailsForCompanyGroupOperationCompleted(object arg) {
            if ((this.lostDetailsForCompanyGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lostDetailsForCompanyGroupCompleted(this, new lostDetailsForCompanyGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/HappyTailList", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] HappyTailList(string pAuthKey, int pSpeciesID, int pSiteID, string pOrderBy, int pCount, string pFeaturedPet) {
            object[] results = this.Invoke("HappyTailList", new object[] {
                        pAuthKey,
                        pSpeciesID,
                        pSiteID,
                        pOrderBy,
                        pCount,
                        pFeaturedPet});
            return ((object[])(results[0]));
        }
        
        /// CodeRemarks
        public void HappyTailListAsync(string pAuthKey, int pSpeciesID, int pSiteID, string pOrderBy, int pCount, string pFeaturedPet) {
            this.HappyTailListAsync(pAuthKey, pSpeciesID, pSiteID, pOrderBy, pCount, pFeaturedPet, null);
        }
        
        /// CodeRemarks
        public void HappyTailListAsync(string pAuthKey, int pSpeciesID, int pSiteID, string pOrderBy, int pCount, string pFeaturedPet, object userState) {
            if ((this.HappyTailListOperationCompleted == null)) {
                this.HappyTailListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHappyTailListOperationCompleted);
            }
            this.InvokeAsync("HappyTailList", new object[] {
                        pAuthKey,
                        pSpeciesID,
                        pSiteID,
                        pOrderBy,
                        pCount,
                        pFeaturedPet}, this.HappyTailListOperationCompleted, userState);
        }
        
        private void OnHappyTailListOperationCompleted(object arg) {
            if ((this.HappyTailListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HappyTailListCompleted(this, new HappyTailListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petango.com/HappyTailDetails", RequestNamespace="http://www.petango.com/", ResponseNamespace="http://www.petango.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HappyTailDetailItem[] HappyTailDetails(string pAuthkey, int pAdoptionID) {
            object[] results = this.Invoke("HappyTailDetails", new object[] {
                        pAuthkey,
                        pAdoptionID});
            return ((HappyTailDetailItem[])(results[0]));
        }
        
        /// CodeRemarks
        public void HappyTailDetailsAsync(string pAuthkey, int pAdoptionID) {
            this.HappyTailDetailsAsync(pAuthkey, pAdoptionID, null);
        }
        
        /// CodeRemarks
        public void HappyTailDetailsAsync(string pAuthkey, int pAdoptionID, object userState) {
            if ((this.HappyTailDetailsOperationCompleted == null)) {
                this.HappyTailDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHappyTailDetailsOperationCompleted);
            }
            this.InvokeAsync("HappyTailDetails", new object[] {
                        pAuthkey,
                        pAdoptionID}, this.HappyTailDetailsOperationCompleted, userState);
        }
        
        private void OnHappyTailDetailsOperationCompleted(object arg) {
            if ((this.HappyTailDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HappyTailDetailsCompleted(this, new HappyTailDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HappyTailDetailItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.petango.com/")]
    public partial class HappyTailListItem {
        
        /// <remarks/>
        public int AdoptionID;
        
        /// <remarks/>
        public System.DateTime AdoptionDate;
        
        /// <remarks/>
        public System.DateTime HappyTExpiryDate;
        
        /// <remarks/>
        public int AnimalID;
        
        /// <remarks/>
        public int CompanyID;
        
        /// <remarks/>
        public int ShelterID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Species;
        
        /// <remarks/>
        public int SpeciesID;
        
        /// <remarks/>
        public string Sex;
        
        /// <remarks/>
        public int SiteID;
        
        /// <remarks/>
        public string PostZipCode;
        
        /// <remarks/>
        public System.DateTime DateOfBirth;
        
        /// <remarks/>
        public string SpayedNeutered;
        
        /// <remarks/>
        public bool SpecialNeeds;
        
        /// <remarks/>
        public string Size;
        
        /// <remarks/>
        public string PrimaryBreed;
        
        /// <remarks/>
        public int PrimaryBreedID;
        
        /// <remarks/>
        public string SecondaryBreed;
        
        /// <remarks/>
        public int SecondaryBreedID;
        
        /// <remarks/>
        public string AgeGroup;
        
        /// <remarks/>
        public int AgeGroupID;
        
        /// <remarks/>
        public string Photo;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.petango.com/")]
    public partial class HappyTailDetailItem : HappyTailListItem {
        
        /// <remarks/>
        public string HouseTrained;
        
        /// <remarks/>
        public string PrimaryColor;
        
        /// <remarks/>
        public int PrimaryColorID;
        
        /// <remarks/>
        public string SecondaryColor;
        
        /// <remarks/>
        public int SecondaryColorID;
        
        /// <remarks/>
        public string Declawed;
        
        /// <remarks/>
        public string Photo2;
        
        /// <remarks/>
        public string Photo3;
        
        /// <remarks/>
        public string Memo;
        
        /// <remarks/>
        public string ShelterMicrosite;
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void MedicalViewReportPdfCompletedEventHandler(object sender, MedicalViewReportPdfCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MedicalViewReportPdfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MedicalViewReportPdfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void AdoptionDetailsCompletedEventHandler(object sender, AdoptionDetailsCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdoptionDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdoptionDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void AdoptionListCompletedEventHandler(object sender, AdoptionListCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdoptionListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdoptionListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void AdoptableSearchCompletedEventHandler(object sender, AdoptableSearchCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdoptableSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdoptableSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void AdoptableSearchWithStageCompletedEventHandler(object sender, AdoptableSearchWithStageCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdoptableSearchWithStageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdoptableSearchWithStageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void AdoptableDetailsCompletedEventHandler(object sender, AdoptableDetailsCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdoptableDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AdoptableDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void foundSearchCompletedEventHandler(object sender, foundSearchCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class foundSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal foundSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void foundSearchForCompanyGroupCompletedEventHandler(object sender, foundSearchForCompanyGroupCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class foundSearchForCompanyGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal foundSearchForCompanyGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void foundSearchForCompanyGroupPageableCompletedEventHandler(object sender, foundSearchForCompanyGroupPageableCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class foundSearchForCompanyGroupPageableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal foundSearchForCompanyGroupPageableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void foundSearchWithSiteCompletedEventHandler(object sender, foundSearchWithSiteCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class foundSearchWithSiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal foundSearchWithSiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void lostSearchCompletedEventHandler(object sender, lostSearchCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lostSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lostSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void lostSearchForCompanyGroupCompletedEventHandler(object sender, lostSearchForCompanyGroupCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lostSearchForCompanyGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lostSearchForCompanyGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void lostSearchForCompanyGroupPageableCompletedEventHandler(object sender, lostSearchForCompanyGroupPageableCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lostSearchForCompanyGroupPageableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lostSearchForCompanyGroupPageableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void foundDetailsCompletedEventHandler(object sender, foundDetailsCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class foundDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal foundDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void foundDetailsForCompanyGroupCompletedEventHandler(object sender, foundDetailsForCompanyGroupCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class foundDetailsForCompanyGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal foundDetailsForCompanyGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void lostDetailsCompletedEventHandler(object sender, lostDetailsCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lostDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lostDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void lostDetailsForCompanyGroupCompletedEventHandler(object sender, lostDetailsForCompanyGroupCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lostDetailsForCompanyGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lostDetailsForCompanyGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void HappyTailListCompletedEventHandler(object sender, HappyTailListCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HappyTailListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HappyTailListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    public delegate void HappyTailDetailsCompletedEventHandler(object sender, HappyTailDetailsCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.8.3.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HappyTailDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HappyTailDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public HappyTailDetailItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HappyTailDetailItem[])(this.results[0]));
            }
        }
    }
}
